server:
  port: 8081

spring:
  application:
    name: user-service
  data:
    mongodb:
      uri: mongodb://mongodb:27017/userdb
      #uri: mongodb://localhost:27017/userdb

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka
     # defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

